project:
  type: website

website:
  navbar:
    title: false
    search: false
    left: []
    right: []
  sidebar: false

format:
  html:
    include-in-header: includes/iconify.html
    include-before-body: includes/icon-sidebar.html
    theme:
      light: [default, scss/theme-light.scss]
      dark:  [default, scss/theme-dark.scss]
    grid:
      body-width: 680px
      margin-width: 260px
    highlight-style: github
    css: styles.css
    toc: true
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true